default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  url: postgresql://username:passowrd@localhost:5432/db?encoding=utf8&pool=5&timeout=5000

test:
  <<: *default
  url: postgresql://username:passowrd@localhost:5432/db_test?encoding=utf8&pool=5&timeout=5000

production:
  <<: *default
