default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  url: postgresql://postgres:postgres@localhost:5432/booking_app?encoding=utf8&pool=5&timeout=5000

test:
  <<: *default
  url: postgresql://postgres:postgres@localhost:5432/booking_app_test?encoding=utf8&pool=5&timeout=5000

production:
  <<: *default
